version: '3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=tasksdatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=Password1
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=sunnytodolist
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=Password1
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

volumes:
   postgres_data: