# Generated by Django 4.2.13 on 2024-05-23 13:54
from django.db import migrations


def create_initial_locations(apps, schema_editor):
    location = apps.get_model('tasks', 'Location')
    initial_locations = [
        'London',
        'Warsaw',
        'Berlin',
        'Kyiv',
        'Madrid',
        'Paris',
        'Rome',
        'Prague',
        'Stockholm',
        'Sofia',
        'Bucharest',
        'Zurich',
    ]
    for location_name in initial_locations:
        location.objects.create(name=location_name)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_locations),
    ]
